color: null
fieldLayouts:
  67823bf4-b8aa-41fd-9ac2-28f3e4a7e4c2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b216b181-3b5f-4acd-9a58-398daafce66c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 18c0c988-558c-4019-bdde-b416c46dcb62 # Image Link Card
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1460426a-8200-408a-845e-d1cc9af60028
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d12e6fdb-cb4d-44bb-888d-57ad86c51b1a
        userCondition: null
handle: imageLinkCard
hasTitleField: true
icon: ''
name: 'Image Link Card'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
