altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  843ef37b-e8dc-4aa9-9ac9-11241cf101f4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d0d23b4b-00b5-44ee-aa55-298a826353b5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2c9032ea-1bf6-4bc3-9302-02e5266918c6
        userCondition: null
fs: images
handle: image
name: Image
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
