dateModified: 1718376838
email:
  fromEmail: motamonteiro@gmail.com
  fromName: 'Test Plugin'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    ca1295fa-55d9-492f-8dc9-c510f11bfe0c: 'Test Plugin' # Test Plugin
    ef9a3e8f-0b5d-446e-93a3-28aa6505786c: 'Test Plugin' # Test Plugin
plugins:
  entry-explorer:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Test Plugin'
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
